version: '3.0'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    image: schedule-worker
    container_name: schedule-worker-node
    restart: unless-stopped
    ports:
      - '5000:5000'
    expose:
      - '5000'
