version: "3"

volumes:
  db: # mount it internally instead of a folder. it avoids file lock problems

services:
  node:
    env_file:
      - .env
    container_name: scheduler-worker
    restart: always
    build: .
    ports:
      - "5000:5000"
